version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: snapbook-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: snapbook_db
      MYSQL_USER: snapbook_user
      MYSQL_PASSWORD: snapbook1234
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: snapbook-app
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: loadtest
      DB_HOST: jdbc:mysql://mysql:3306/snapbook_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
      DB_USERNAME: snapbook_user
      DB_PASSWORD: snapbook1234
      JWT_SECRET_KEY: MtpnAj36OdimOlI8eHfz+Kio8KJyB7rkQrTQ7oS9hjA=
      KAKAO_CLIENT_ID: ef7ce0ec61ee7af5535c003cf8808fc6
    ports:
      - "8081:8080"
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost:8080/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  mysql_data: