spring:
  application:
    name: snapbook

---

spring:
  config:
    activate:
      on-profile: local
  application:
    name: snapbook
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  kakao:
    auth:
      client: ${KAKAO_CLIENT_ID}
      redirect: http://localhost:8080/oauth/login/kakao
jwt:
  secret: ${JWT_SECRET_KEY}
  access-token-expiration: 3600000
  refresh-token-expiration: 604800000

---

spring:
  config:
    activate:
      on-profile: dev
  application:
    name: snapbook
  datasource:
    url: ${DB_HOST}
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  kakao:
    auth:
      client: ${KAKAO_CLIENT_ID}
      redirect: http://localhost:5173/auth
jwt:
  secret: ${JWT_SECRET_KEY}
  access-token-expiration: 3600000
  refresh-token-expiration: 604800000
