spring:
  application:
    name: easybooking
  datasource:
    url: jdbc:mysql://localhost:3306/easybooking?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=utf8
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: qwer1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  kakao:
    auth:
      client: ef7ce0ec61ee7af5535c003cf8808fc6
      redirect: http://localhost:8080/oauth/login/kakao