spring:
  application:
    name: snapbook
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

aws:
  s3:
    bucket: snapbook-bucket
    base-url: https://snapbook-bucket.s3.ap-northeast-2.amazonaws.com/
    region: ${AWS_REGION}
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}

---

spring:
  config:
    activate:
      on-profile: local
  application:
    name: snapbook
  datasource:
    url: jdbc:h2:file:./data/testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  kakao:
    auth:
      client: ${KAKAO_CLIENT_ID}
      redirect: http://localhost:8080/oauth/login/kakao
jwt:
  secret: ${JWT_SECRET_KEY}
  access-token-expiration: 31536000000  # 로컬 테스트용, 유효기간 1년
  refresh-token-expiration: 3153600000

---

spring:
  config:
    activate:
      on-profile: dev
  application:
    name: snapbook
  datasource:
    url: ${DB_HOST}
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  kakao:
    auth:
      client: ${KAKAO_CLIENT_ID}
      redirect: http://localhost:5173/auth
jwt:
  secret: ${JWT_SECRET_KEY}
  access-token-expiration: 3600000
  refresh-token-expiration: 2592000000
