spring:
  application:
    name: snapbook

---

spring:
  config:
    activate:
      on-profile: local
  application:
    name: snapbook
  datasource:
    url: {LOCAL_DB_HOST}
    driverClassName: com.mysql.cj.jdbc.Driver
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  kakao:
    auth:
      client: {KAKAO_CLIENT_ID}
      redirect: http://localhost:8080/oauth/login/kakao
jwt:
  secret: ${JWT_SECRET_KEY}
  access-token-expiration: 3600000
  refresh-token-expiration: 604800000

---

spring:
  config:
    activate:
      on-profile: dev
  application:
    name: snapbook
  datasource:
    url: {DB_HOST}
    driverClassName: com.mysql.cj.jdbc.Driver
    username: {DB_USERNAME}
    password: {DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  kakao:
    auth:
      client: {KAKAO_CLIENT_ID}
      redirect: http://localhost:8080/oauth/login/kakao
jwt:
  secret: ${JWT_SECRET_KEY}
  access-token-expiration: 3600000
  refresh-token-expiration: 604800000