CREATE TABLE shop_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shop_id BIGINT NOT NULL,
  interval_minutes INT NOT NULL,
  schedule_type VARCHAR(30) NOT NULL,
  booking_window_days INT NOT NULL,
  min_booking_lead_minutes INT NOT NULL,
  public_holiday_off BOOLEAN NOT NULL
);

CREATE TABLE shop_operating_times (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shop_id BIGINT NOT NULL,
  day_of_week VARCHAR(10) NOT NULL,
  start_time TIME NOT NULL,
  end_time TIME NOT NULL,
  sort_order INT NOT NULL
);

CREATE TABLE staff_operating_times (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  staff_id BIGINT NOT NULL,
  day_of_week VARCHAR(10) NOT NULL,
  is_off BOOLEAN NOT NULL,
  start_time TIME,
  end_time TIME
);

CREATE TABLE shop_holidays (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shop_id BIGINT NOT NULL,
  holiday_type VARCHAR(20) NOT NULL,
  day_of_week VARCHAR(10),
  week_of_month INT,
  reference_date DATE,
  specific_date DATE
);

CREATE TABLE public_holidays (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  holiday_date DATE NOT NULL,
  name VARCHAR(100)
);
