CREATE TABLE IF NOT EXISTS tags (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  CONSTRAINT uq_tags_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS shop_menus (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shop_id BIGINT NOT NULL,
  name VARCHAR(255) NOT NULL,
  is_active BOOLEAN NOT NULL,
  sort_order INT NOT NULL
);

CREATE TABLE IF NOT EXISTS shop_menu_tags (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shop_menu_id BIGINT NOT NULL,
  tag_id BIGINT,
  CONSTRAINT uq_shop_menu_tags UNIQUE (shop_menu_id, tag_id)
);

CREATE TABLE shop_tags (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shop_id BIGINT NOT NULL,
  name VARCHAR(100) NOT NULL,
  sort_order INT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_shop_tags_shop_name UNIQUE (shop_id, name),
  CONSTRAINT uq_shop_tags_shop_sort UNIQUE (shop_id, sort_order)
);

CREATE INDEX idx_shop_tags_shop_sort
  ON shop_tags (shop_id, sort_order);
